<a href="https://colab.research.google.com/github/sandeepsinghsengar/MPU/blob/master/MPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive


In [3]:
!ls

drive  sample_data


In [4]:
%cd drive/My Drive/MPU_Project


/content/drive/My Drive/MPU_Project


In [ ]:
! git clone https://github.com/perslev/MultiPlanarUNet.git


fatal: destination path 'MultiPlanarUNet' already exists and is not an empty directory.


In [ ]:
! git init

Reinitialized existing Git repository in /content/drive/My Drive/MPU_Project/.git/


In [ ]:
! git pull MultiPlanarUNet


From MultiPlanarUNet
 * branch            HEAD       -> FETCH_HEAD
Already up to date.


In [5]:
%cd mpunet/



/content/drive/My Drive/MPU_Project/mpunet


In [8]:
!pwd

/content/drive/My Drive/MPU_Project/mpunet


In [6]:
!pip install mpunet

     |████████████████████████████████| 133kB 9.4MB/s 
     |████████████████████████████████| 11.6MB 13.0MB/s 
     |████████████████████████████████| 14.5MB 240kB/s 
     |████████████████████████████████| 3.3MB 45.7MB/s 
     |████████████████████████████████| 112kB 55.8MB/s 
     |████████████████████████████████| 6.8MB 51.0MB/s 
     |████████████████████████████████| 471kB 44.4MB/s 
     |████████████████████████████████| 1.1MB 42.6MB/s 
     |████████████████████████████████| 516.2MB 34kB/s 
     |████████████████████████████████| 552kB 99kB/s 
     |████████████████████████████████| 3.0MB 42.9MB/s 
     |████████████████████████████████| 460kB 54.1MB/s 
  Created wheel for mpunet: filename=mpunet-0.2.7-cp36-none-any.whl size=175947 sha256=af1cf4813edd2b0ae0d0dd269b2a7ecf28410e76a4772d3279803115ac360e7a
  Stored in directory: /root/.cache/pip/wheels/8e/8d/3c/ef7a51c182de5e160452ea449065bbca34537598676a668da1
  Created wheel for psutil: filename=psutil-5.7.3-cp36-cp36m-linux_x86_

In [7]:
!mp --help

usage: mp [script] [script args...]

Multi-Planar UNet (0.2.7)
-------------------------
Available scripts:
- branch
- cv_experiment
- cv_split
- init_project
- predict
- predict_3D
- run_tests
- summary
- toy_data
- train
- train_fusion
- trim_channels

positional arguments:
  {branch,cv_experiment,cv_split,init_project,predict,predict_3D,run_tests,summary,toy_data,train,train_fusion,trim_channels}
                        Name of the mp script to run.
  args                  Arguments passed to script

optional arguments:
  -h, --help            show this help message and exit


In [9]:
!mp init_project --name my_project --data_dir data_folder


Setting value '/content/drive/My Drive/MPU_Project/mpunet/data_folder/train' (type <class 'str'>) in subdir 'train_data' with name 'base_dir'
Setting value '/content/drive/My Drive/MPU_Project/mpunet/data_folder/val' (type <class 'str'>) in subdir 'val_data' with name 'base_dir'
Setting value '/content/drive/My Drive/MPU_Project/mpunet/data_folder/test' (type <class 'str'>) in subdir 'test_data' with name 'base_dir'
Setting value '/content/drive/My Drive/MPU_Project/mpunet/data_folder/aug' (type <class 'str'>) in subdir 'aug_data' with name 'base_dir'


In [10]:
!pip install tensorflow==2.2

     |████████████████████████████████| 516.2MB 32kB/s 
  Found existing installation: tensorflow 2.3.0
    Uninstalling tensorflow-2.3.0:
      Successfully uninstalled tensorflow-2.3.0


In [11]:
!pwd
%cd my_project/


/content/drive/My Drive/MPU_Project/mpunet
/content/drive/My Drive/MPU_Project/mpunet/my_project


In [ ]:
!mp train --overwrite

--------------------------------------------------------------------------------
>>> Logged by: 'entry_func' in 'train.py'
Fitting model in path:
/content/drive/My Drive/MPU_Project/mpunet/my_project
--------------------------------------------------------------------------------
>>> Logged by: '__init__' in 'hparams.py'
YAML path:    /content/drive/My Drive/MPU_Project/mpunet/my_project/train_hparams.yaml
[WARNING] Path /usr/local/lib/python3.6/dist-packages does not contain a Git repository, or Git is not installed on this system.
-- The software verison match could not be varified against the hyperparameter file.
-- Software version will not be added to the hyperparameter file.
--------------------------------------------------------------------------------
>>> Logged by: '_base_loader_func' in 'data_preparation_funcs.py'
Looking for images...
--------------------------------------------------------------------------------
>>> Logged by: '_log' in 'image_pair_loader.py'
ImagePairLoa

In [ ]:
!ls
%cd mpunet/my_project


HISTORY.rst  MANIFEST.in  mpunet	   README.md	     resources
LICENSE.txt  MPU.ipynb	  MultiPlanarUNet  requirements.txt  setup.py
/content/drive/My Drive/MPU_Project/mpunet/my_project


In [ ]:
!mp train_fusion --overwrite


Fitting fusion model for project-folder: /content/drive/My Drive/MPU_Project/mpunet/my_project
Waiting for free GPU.
Found free GPU: 0
YAML path:    /content/drive/My Drive/MPU_Project/mpunet/my_project/train_hparams.yaml
[WARNING] Path /usr/local/lib/python3.6/dist-packages does not contain a Git repository, or Git is not installed on this system.
-- The software verison match could not be varified against the hyperparameter file.
-- Software version will not be added to the hyperparameter file.
--------------------------------------------------------------------------------
>>> Logged by: 'log' in 'train_fusion.py'
N classes:       9
Scaler:          RobustScaler
Crop:            None
Downsample:      None
CF factor:       2
Views:           [[ 0.13502876  0.89220743  0.43096768]
 [-0.14283512 -0.29724643  0.94405651]
 [-0.54508175 -0.62880921  0.55451317]
 [-0.28087439  0.73768053  0.61395196]
 [-0.92385413 -0.38271765  0.00455514]
 [ 0.11169348  0.02217583  0.99349524]]
Weights:   

In [ ]:
!mp predict --num_GPUs=2 --out_dir predictions


YAML path:    /content/drive/My Drive/MPU_Project/mpunet/my_project/train_hparams.yaml
[WARNING] Path /usr/local/lib/python3.6/dist-packages does not contain a Git repository, or Git is not installed on this system.
-- The software verison match could not be varified against the hyperparameter file.
-- Software version will not be added to the hyperparameter file.
ImagePairLoader(id=test, images=10, data_dir=/content/drive/My Drive/MPU_Project/mpunet/data_folder/test)
--- Image subdir: /content/drive/My Drive/MPU_Project/mpunet/data_folder/test/images
--- Label subdir: /content/drive/My Drive/MPU_Project/mpunet/data_folder/test/labels
Waiting for free GPU.
Found free GPU: 0

[*] Loading model weights:
 /content/drive/My Drive/MPU_Project/mpunet/my_project/model/@epoch_02_val_dice_0.21153.h5
2020-11-19 14:17:05.575053: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-11-19 14:17:05.624381: I tensorflow/stream_executor/

In [ ]:
!mp predict --no_eval --overwrite


YAML path:    /content/drive/My Drive/MPU_Project/mpunet/my_project/train_hparams.yaml
[WARNING] Path /usr/local/lib/python3.6/dist-packages does not contain a Git repository, or Git is not installed on this system.
-- The software verison match could not be varified against the hyperparameter file.
-- Software version will not be added to the hyperparameter file.
ImagePairLoader(id=test, images=10, data_dir=/content/drive/My Drive/MPU_Project/mpunet/data_folder/test)
--- Image subdir: /content/drive/My Drive/MPU_Project/mpunet/data_folder/test/images
--- Label subdir: None
Waiting for free GPU.
Found free GPU: 0

[*] Loading model weights:
 /content/drive/My Drive/MPU_Project/mpunet/my_project/model/@epoch_02_val_dice_0.21153.h5
2020-11-19 14:28:34.716813: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-11-19 14:28:34.772450: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from 

In [ ]:
!pwd


/content/drive/My Drive/MPU_Project/mpunet/my_project


In [ ]:
%cd /content/drive/My Drive/MPU_Project/mpunet/my_project


/content/drive/My Drive/MPU_Project/mpunet/my_project


In [ ]:
!mp predict -f 9902757_20041112_SAG_3D_DESS_RIGHT_016610077012.mat.nii.gz --continue



YAML path:    /content/drive/My Drive/MPU_Project/mpunet/my_project/train_hparams.yaml
[WARNING] Path /usr/local/lib/python3.6/dist-packages does not contain a Git repository, or Git is not installed on this system.
-- The software verison match could not be varified against the hyperparameter file.
-- Software version will not be added to the hyperparameter file.
ImagePairLoader(id=my_project, images=0, data_dir=/content/drive/My Drive/MPU_Project/mpunet/my_project)
--- Image subdir: /content/drive/My Drive/MPU_Project/mpunet/my_project/images
--- Label subdir: None
[OBS] Not predicting on images: [] (--continue mode)
Waiting for free GPU.
Found free GPU: 0

[*] Loading model weights:
 /content/drive/My Drive/MPU_Project/mpunet/my_project/model/@epoch_02_val_dice_0.21153.h5
2020-11-19 14:47:47.308002: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-11-19 14:47:47.369709: I tensorflow/stream_executor/cuda/cuda_gpu_ex

In [ ]:
!mp predict -f 9902757_20041112_SAG_3D_DESS_RIGHT_016610077012.mat.nii.gz -l images/9902757_20041112_SAG_3D_DESS_RIGHT_016610077012.mat.nii.gz --continue


YAML path:    /content/drive/My Drive/MPU_Project/mpunet/my_project/train_hparams.yaml
[WARNING] Path /usr/local/lib/python3.6/dist-packages does not contain a Git repository, or Git is not installed on this system.
-- The software verison match could not be varified against the hyperparameter file.
-- Software version will not be added to the hyperparameter file.
ImagePairLoader(id=my_project, images=0, data_dir=/content/drive/My Drive/MPU_Project/mpunet/my_project)
--- Image subdir: /content/drive/My Drive/MPU_Project/mpunet/my_project/images
--- Label subdir: /content/drive/My Drive/MPU_Project/mpunet/my_project/labels
[OBS] Not predicting on images: [] (--continue mode)
Waiting for free GPU.
Found free GPU: 0

[*] Loading model weights:
 /content/drive/My Drive/MPU_Project/mpunet/my_project/model/@epoch_02_val_dice_0.21153.h5
2020-11-19 14:59:58.801705: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-11-19 14:59:

In [ ]:
!mp summary


Found 1 'csv' folders under prediction dirs 'predictions':
-- /content/drive/My Drive/MPU_Project/mpunet/my_project/predictions/csv

Correct? (Y/n) y

[***] SUMMARY REPORT FOR FOLDER [***]
/content/drive/My Drive/MPU_Project/mpunet/my_project/predictions/csv/

/usr/local/lib/python3.6/dist-packages/mpunet/bin/summary.py:35: RuntimeWarning: Mean of empty slice
  means = np.nanmean(ddf.values, axis=1)
/usr/local/lib/python3.6/dist-packages/numpy/lib/nanfunctions.py:1665: RuntimeWarning: Degrees of freedom <= 0 for slice.
  keepdims=keepdims)
/usr/local/lib/python3.6/dist-packages/mpunet/bin/summary.py:37: RuntimeWarning: All-NaN slice encountered
  mins = np.nanmin(ddf.values, axis=1)
/usr/local/lib/python3.6/dist-packages/mpunet/bin/summary.py:38: RuntimeWarning: All-NaN slice encountered
  maxs = np.nanmax(ddf.values, axis=1)

Per class:
--------------------------------
   Mean dice by class  ...    N
1                 NaN  ...  0.0
2                 NaN  ...  0.0
3                 NaN

In [ ]:
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))


Found GPU at: /device:GPU:0
